app_project/config/routes.rb
Rails.application.routes.draw do
  
  root 'players#index'
  resources :players
  resources :games do 
    resources :scores
  end
  

end

app_project/app/models/game.rb
class Game < ActiveRecord::Base
    has_many :scores
    has_many :players, through: :scores
end

app_project/app/models/player.rb
class Player < ActiveRecord::Base
    has_many :scores
    has_many :games, through: :scores
end

app_project/app/models/score.rb
class Score < ActiveRecord::Base
    belongs_to :game 
    belongs_to :player
end

app_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app_project/app/controllers/games_controller.rb
class GamesController < ApplicationController
 def new
        @game = Game.new
    end
    def create
        @game = Game.new(game_params)
        @game.save
        redirect_to @game
    end
        def show 
            @game=Game.find(params[:id])
        end
        def index
            @games = Game.all
        end
        def edit
            @game=Game.find(params[:id])
        end
        def update
            @game=Game.find(params[:id])
            @game.update(game_params)
            redirect_to @game 
        end
        def destroy
            @game=Game.find(params[:id])
            @game.destroy 
            redirect_to games_path
        end 
            
        private
        def game_params
            params.require(:game).permit(:home_team,:away_team,:field,:date)
        end
end

app_project/app/controllers/players_controller.rb
class PlayersController < ApplicationController
    def new
        @player = Player.new
    end
    def create
        @player = Player.new(player_params)
        @player.save
        redirect_to @player
    end
        def show 
            @player=Player.find(params[:id])
        end
        def index
            @players = Player.all
        end
        def edit
            @player=Player.find(params[:id])
        end
        def update
            @player=Player.find(params[:id])
            @player.update(player_params)
            redirect_to @player 
        end
        def destroy
            @player=Player.find(params[:id])
            @player.destroy 
            redirect_to players_path
        end 
            
        private
        def player_params
            params.require(:player).permit(:first_name,:last_name,:number,:position)
        end
end

app_project/app/controllers/scores_controller.rb
class ScoresController < ApplicationController
    def new
    @game = Game.find(params[:game_id])
    @score = Score.new
end

def create
        @game = Game.find(params[:game_id])
        
        if @game.scores.create(score_params)
            redirect_to @game
        else
            render 'new'
        end
    end
    private
    def score_params
        params.require(:score).permit(:time,:assist_or_goal,:player_id,:game_id)
    end
end

app_project/app/helpers/application_helper.rb
module ApplicationHelper
end

app_project/app/helpers/games_helper.rb
module GamesHelper
end

app_project/app/helpers/players_helper.rb
module PlayersHelper
end

app_project/app/helpers/scores_helper.rb
module ScoresHelper
end

app_project/app/views/games/_form.html.erb
<%= form_for @game do |f| %>
    <p>
            <%= f.label :date %>
           <%= f.date_select :date, order: [:month, :day, :year], start_year: 1900, :class => 'form_control' %>
    </p>
     <p>
            <%= f.label :field %>
            <%= f.text_field :field, :class => 'form-control'%>
    </p>
    <p>
        <%= f.label :home_team %>
        <%= f.text_field :home_team, :class => 'form-control'%>
    </p>
    <p>
        <%= f.label :away_team %>
        <%= f.text_field :away_team, :class => 'form-control'%>
    </p>
    <p>
        <%= f.submit%>
    </p>
<% end %>

app_project/app/views/games/edit.html.erb
<div class="panel-heading">
    
        <h1 class= "panel-title">Edit Game</h1>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>

app_project/app/views/games/index.html.erb
<h1>All Games</h1>
<table class="table">
    <tr>
        <th>Home team Away Team</th>
        <th>Date</th>
        <th>Field</th>
    </tr>
    <%@games.each do |game|%>
    
    <tr>
        <td><%=link_to game.home_team,game%> <%=game.away_team%></td>
        <td><%=game.date%></td>
        <td><%=game.field%></td>
        <td><%=link_to 'edit', edit_game_path(game)%>
         <%= link_to 'Delete', game_path(game), method: :delete, data: { confirm: "Are you sure you want to delete this game?" } %>
        </td>
    </tr>
    <% end %>
</table>

app_project/app/views/games/new.html.erb
<div class="panel-heading">
        <h1 class= "panel-title">New Game</h1>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>

app_project/app/views/games/show.html.erb
<h1><%= @game.home_team %> vs <%= @game.away_team %></h1>
<p>Date: <%=@game.date%></p>
<p>field: <%=@game.field%></p>
<h2>scores</h2>
<ul>
    <% @game.scores.each do |score|%>
    <li>
        <%= score.player.first_name%> <%= score.player.last_name%>
        <%= score.time%>th minute
    </li>
    <% end %>
</ul>
<p><%=link_to 'Add Score',new_game_score_path(@game)%></p>

app_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lax App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#main-menu">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'App', root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="main-menu">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Players', players_path %></li>
        <li><%= link_to 'New Player', new_player_path %></li>
         <li><%= link_to 'Games', games_path %></li>
        <li><%= link_to 'New Games', new_game_path %></li>
      </ul>
    </div>
  </nav>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app_project/app/views/players/_form.html.erb
<%= form_for @player do |f| %>
    <p>
            <%= f.label :first_name %>
            <%= f.text_field :first_name, :class => 'form-control'%>
    </p>
     <p>
            <%= f.label :last_name %>
            <%= f.text_field :last_name, :class => 'form-control'%>
    </p>
    <p>
        <%= f.label :number %>
        <%= f.text_field :number, :class => 'form-control'%>
    </p>
    <p>
        <%= f.label :position %>
        <%= f.text_field :position, :class => 'form-control'%>
    </p>
    <p>
        <%= f.submit%>
    </p>
<% end %>

app_project/app/views/players/edit.html.erb
<div class="panel-heading">
        <h1 class= "panel-title">Edit Player</h1>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>

app_project/app/views/players/index.html.erb
<h1>All Players</h1>
<table class="table">
    <tr>
        <th>Player Name</th>
        <th>Position</th>
        <th>Number</th>
        <th></th>
    </tr>
    <%@players.each do |player|%>
    
    <tr>
        <td><%=player.first_name%> <%=player.last_name%></td>
        <td><%=player.position%></td>
        <td><%=player.number%></td>
        <td><%=link_to 'edit', edit_player_path(player)%>
         <%= link_to 'Delete', player_path(player), method: :delete, data: { confirm: "Are you sure you want to delete #{player.first_name}?" } %>
        </td>
    </tr>
    <% end %>
</table>

app_project/app/views/players/new.html.erb
<div class="panel-heading">
        <h1 class= "panel-title">New Player</h1>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>

app_project/app/views/players/show.html.erb
<h1><%= @player.first_name %> <%= @player.last_name %></h1>
<p>position: <%=@player.position%></p>
<p>number: <%=@player.number%></p>

app_project/app/views/scores/_form.html.erb
<%= form_for [@game,@score] do |f| %>
<div class="form-group">
        <%= f.label :player_id %>
        <br>
        <%= f.select :player_id, Player.all.collect { |a| [a.first_name, a.id] }, :class => 'form-control' %>
    </div>
    <p>
            <%= f.label :assist_or_goal %>
           <%= f.select :assist_or_goal, { score: 'Score', assist: 'Assist' }, :class => 'form_control' %>
    </p>
     <p>
            <%= f.label :time %>
            <%= f.text_field :time, :class => 'form-control'%>
    </p>
    <p>
        <%= f.submit%>
    </p>
<% end %>

app_project/app/views/scores/new.html.erb
<div class="panel-heading">
        <h1 class= "panel-title">New cores</h1>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>